import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaCamera, FaUserCircle, FaSave, FaSignOutAlt } from "react-icons/fa";

function AdminProfile() {
  const navigate = useNavigate(); const fileRef = useRef(null);
  const current = JSON.parse(localStorage.getItem("admin"));
  const [form, setForm] = useState(() => ({ name: current?.name || "", email: current?.email || "", phone: current?.phone || "", password: "", profileImage: current?.profileImage || "" }));
  if (!current) { navigate("/login"); return null; }
  const update = (key, value) => setForm((previous) => ({ ...previous, [key]: value }));
  const save = (event) => { event.preventDefault(); if (!form.name.trim() || !form.email.trim()) return alert("Name and email are required."); const updated = { ...current, name: form.name.trim(), email: form.email.trim(), phone: form.phone.trim(), profileImage: form.profileImage, ...(form.password ? { password: form.password } : {}) }; localStorage.setItem("admin", JSON.stringify(updated)); const admins = JSON.parse(localStorage.getItem("admins")) || []; localStorage.setItem("admins", JSON.stringify(admins.map((admin) => admin.id === updated.id ? updated : admin))); localStorage.setItem("users", JSON.stringify((JSON.parse(localStorage.getItem("users")) || []).map((user) => user.id === updated.id ? updated : user))); alert("Profile updated successfully."); };
  const image = (event) => { const file=event.target.files?.[0]; if (!file) return; const reader=new FileReader(); reader.onload=()=>update("profileImage",reader.result); reader.readAsDataURL(file); };
  return <div className="mx-auto max-w-3xl"><div className="mb-7"><p className="eyebrow">Account settings</p><h1 className="mt-3 text-3xl font-black text-slate-950">My profile</h1><p className="mt-2 text-slate-500">Manage your admin account details securely.</p></div><form onSubmit={save} className="soft-card overflow-hidden"><div className="h-28 bg-gradient-to-r from-blue-700 to-indigo-600"/><div className="px-5 pb-6 sm:px-8"><div className="-mt-14 flex flex-col items-center gap-4 sm:flex-row sm:items-end"><div className="relative"><div className="grid h-28 w-28 place-items-center overflow-hidden rounded-3xl border-4 border-white bg-slate-100 text-6xl text-blue-600 shadow-xl">{form.profileImage ? <img src={form.profileImage} alt="Profile" className="h-full w-full object-cover"/> : <FaUserCircle />}</div><button type="button" onClick={()=>fileRef.current?.click()} className="absolute -bottom-2 -right-2 grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white shadow-lg"><FaCamera /></button><input ref={fileRef} type="file" accept="image/*" onChange={image} className="hidden"/></div><div className="pb-1 text-center sm:text-left"><h2 className="text-xl font-black text-slate-950">{form.name || "Admin"}</h2><p className="mt-1 text-sm text-slate-500">{current.role}</p></div></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Full name" value={form.name} onChange={(e)=>update("name",e.target.value)} /><Field label="Email address" type="email" value={form.email} onChange={(e)=>update("email",e.target.value)} /><Field label="Phone number" value={form.phone} onChange={(e)=>update("phone",e.target.value)} /><Field label="New password" type="password" placeholder="Leave blank to keep current" value={form.password} onChange={(e)=>update("password",e.target.value)} /></div><div className="mt-7 flex flex-col gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-between"><button type="button" onClick={()=>{localStorage.removeItem("admin");localStorage.removeItem("role");navigate("/login");}} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold text-rose-600 hover:bg-rose-50"><FaSignOutAlt /> Logout</button><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200 transition hover:bg-blue-800"><FaSave /> Save changes</button></div></div></form></div>;
}
function Field({label,...props}) {return <label className="block text-sm font-bold text-slate-700">{label}<input {...props} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal text-slate-800 outline-none transition focus:border-blue-500 focus:bg-white"/></label>}
export default AdminProfile;
