import { useOrders } from "../Context/Ordercontext";
import { useUser } from "../Context/Usercontext";
import { FaBoxOpen, FaClipboardList, FaUsers, FaWallet, FaArrowUp, FaShoppingBag } from "react-icons/fa";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";

function Overview() {
  const { orders } = useOrders(); const { users } = useUser();
  const orderProducts = orders.flatMap((order) => (order.products || order.items || []).map((product) => ({ ...product, orderId: order.id, status: order.status || "Pending" })));
  const productsSold = orderProducts.reduce((total, product) => total + Number(product.quantity || 1), 0);
  const totalSales = orders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  const chartData = orders.slice(-8).map((order, index) => ({ label: `#${order.id || index + 1}`, sales: Number(order.total || 0) }));
  const recentProducts = orderProducts.slice(-6).reverse();
  return <div className="mx-auto max-w-7xl">
    <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Store performance</p><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Dashboard overview</h1><p className="mt-2 text-slate-500">A live summary of your shop’s orders and sales.</p></div><div className="rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700">Welcome back, Super Admin</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Products sold" value={productsSold} icon={<FaBoxOpen />} color="blue" /><Metric label="Total orders" value={orders.length} icon={<FaClipboardList />} color="violet" /><Metric label="Customers" value={users?.filter((user) => user.role === "User").length || 0} icon={<FaUsers />} color="amber" /><Metric label="Total revenue" value={`$${totalSales.toLocaleString()}`} icon={<FaWallet />} color="emerald" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.9fr]"><section className="soft-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-950">Sales performance</h2><p className="mt-1 text-sm text-slate-500">Revenue from your latest orders</p></div><span className="flex items-center gap-1 rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-600"><FaArrowUp /> Live</span></div><div className="mt-6 h-72">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="sales" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".3"/><stop offset="100%" stopColor="#2563eb" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="4 4"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:"#64748b",fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#64748b",fontSize:12}}/><Tooltip formatter={(value) => [`$${value}`, "Revenue"]}/><Area type="monotone" dataKey="sales" stroke="#2563eb" strokeWidth={3} fill="url(#sales)"/></AreaChart></ResponsiveContainer> : <Empty text="Sales chart will appear after the first order." />}</div></section>
      <section className="soft-card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><FaShoppingBag /></span><div><h2 className="font-bold text-slate-950">Order status</h2><p className="text-sm text-slate-500">Current fulfilment queue</p></div></div><div className="mt-7 space-y-5">{[["Pending","bg-amber-500"],["Processing","bg-blue-500"],["Delivery","bg-violet-500"],["Completed","bg-emerald-500"]].map(([status,color]) => {const count=orders.filter((o)=>o.status===status).length;const pct=orders.length ? Math.round(count/orders.length*100) : 0;return <div key={status}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-slate-700">{status}</span><span className="font-bold text-slate-500">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{width:`${pct}%`}} /></div></div>})}</div></section></div>
    <section className="soft-card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:p-6"><div><h2 className="font-bold text-slate-950">Recently ordered products</h2><p className="mt-1 text-sm text-slate-500">Products ordered by your customers.</p></div><span className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">{orderProducts.length} products</span></div>{recentProducts.length ? <div className="divide-y divide-slate-100">{recentProducts.map((product,index)=><div key={`${product.orderId}-${index}`} className="flex items-center gap-4 p-4 sm:px-6"><img src={product.image} alt={product.name} className="h-14 w-14 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-bold text-slate-900">{product.name}</p><p className="mt-1 text-sm text-slate-500">Order #{product.orderId} · Quantity {product.quantity || 1}</p></div><div className="text-right"><p className="font-bold text-slate-950">${Number(product.price || 0).toLocaleString()}</p><p className="mt-1 text-xs font-semibold text-emerald-600">{product.status}</p></div></div>)}</div> : <div className="p-12"><Empty text="No products have been ordered yet." /></div>}</section>
  </div>;
}
function Metric({label,value,icon,color}) {const colors={blue:"bg-blue-50 text-blue-600",violet:"bg-violet-50 text-violet-600",amber:"bg-amber-50 text-amber-600",emerald:"bg-emerald-50 text-emerald-600"};return <div className="soft-card flex items-center gap-4 p-5"><span className={`grid h-12 w-12 place-items-center rounded-xl ${colors[color]}`}>{icon}</span><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}</p></div></div>}
function Empty({text}) {return <div className="grid h-full place-items-center text-center text-sm text-slate-500">{text}</div>}
export default Overview;
